version: v1.0
name: Deploy to prod
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy
    task:
      env_vars:
        - name: APP_ENV
          value: prod
      jobs:
      - name: deploy
        commands:
          - checkout
          - ls -1
          - echo $APP_ENV
          - echo "Docker build..."
          - echo "done"

